"""Add device_pairing table for Android ID authentication

Revision ID: 11df1596bd76
Revises: e5f6a7b8c9d0
Create Date: 2025-04-02

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '11df1596bd76'
down_revision = 'e5f6a7b8c9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_pairing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('android_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_device_pairing_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('android_id')
    )
    op.create_index('ix_device_pairing_android_id', 'device_pairing', ['android_id'], unique=True)
    op.create_index('ix_device_pairing_id', 'device_pairing', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_pairing_id', table_name='device_pairing')
    op.drop_index('ix_device_pairing_android_id', table_name='device_pairing')
    op.drop_table('device_pairing')
    # ### end Alembic commands ###
