"""add employees table

Revision ID: 260f78639991
Revises: a8193440cdda
Create Date: 2025-03-31 02:02:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '260f78639991'
down_revision = 'a8193440cdda'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nrp', sa.String(length=50), nullable=False),
        sa.Column('nama', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=True),
        sa.Column('section', sa.String(length=100), nullable=False),
        sa.Column('crew', sa.String(length=100), nullable=True),
        sa.Column('posisi', sa.String(length=100), nullable=False),
        sa.Column('target_ss', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('jabatan', sa.String(length=100), nullable=True),
        sa.Column('last_update', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.Index('ix_employees_nrp', 'nrp', unique=True),
        sa.Index('ix_employees_email', 'email', unique=True)
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    # ### end Alembic commands ###
