"""Ensure nrp column exists and is populated, add constraints

Revision ID: a1b2c3d4e5f6
Revises: 11df1596bd76
Create Date: 2025-04-02

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '11df1596bd76'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Try to add nrp column if not exists (catch error if exists)
    try:
        op.add_column('users', sa.Column('nrp', sa.String(length=50), nullable=True))
    except OperationalError as e:
        # Assume column exists if error mentions duplicate column
        if 'Duplicate column name' not in str(e):
            raise
    
    # Populate existing rows: set nrp = email where nrp is NULL or empty
    op.execute("UPDATE users SET nrp = email WHERE nrp IS NULL OR nrp = '';")
    
    # Override for simulator user (id 61122292) with explicit nrp
    op.execute("UPDATE users SET nrp = '61122292' WHERE id = 61122292;")
    
    # Make nrp NOT NULL (after ensuring all rows have value)
    # MySQL requires existing type when altering
    op.alter_column('users', 'nrp', existing_type=sa.String(length=50), nullable=False)
    
    # Create unique index if not exists (ignore error if exists)
    try:
        op.create_index('ix_users_nrp', 'users', ['nrp'], unique=True)
    except OperationalError as e:
        # Index already exists
        if 'Duplicate key name' not in str(e):
            raise
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_index('ix_users_nrp', table_name='users')
    except OperationalError:
        pass
    op.alter_column('users', 'nrp', nullable=True)
    # Note: we don't drop column in downgrade to avoid data loss; can be manual
    # ### end Alembic commands ###
