"""remove last_update from employees

Revision ID: e5f6a7b8c9d0
Revises: 260f78639991
Create Date: 2025-03-31 06:55:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e5f6a7b8c9d0'
down_revision = '260f78639991'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'last_update')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees',
        sa.Column('last_update', sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###
